[build]
  base = "tourify2-main"
  publish = "client/dist"
  command = "npm run build:client"

[[redirects]]
  from = "/api/*"
  to = "https://bb284510-0107-418e-9a16-3f25d1594383-00-22cqmam50o8cd.janeway.replit.dev/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200