[build]
  base = "tourify2-main"
  publish = "client/dist"
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200